name: CI
on:
  push:
    branches:
      - main

env:
  APP_NAME: deployable-env-checker

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          registry-url: https://npm.pkg.github.com
      - run: yarn install
      - run: yarn lint
      - run: yarn typecheck
      - run: yarn build
      - id: packExtensionDir
        uses: cardinalby/webext-buildtools-pack-extension-dir-action@v1
        with:
          extensionDir: "./dist"
          zipFilePath: ${{ env.APP_NAME }}.zip
      - name: Set version to env
        run: node -p -e '`VERSION=${require("./manifest.json").version}`' >> $GITHUB_ENV
      - name: Create release
        id: create_release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ env.VERSION }}
          release_name: Release v${{ env.VERSION }}
          draft: false
          prerelease: false
          files: ${{ env.APP_NAME }}.zip
